{
 "title": "NVIDIA MIG DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster using GPUs in MIG mode",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(DCGM_FI_DEV_FB_FREE, instance)"
   },
   { "name": "gpu", "query": "label_values(gpu)" }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used (Percentage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"} / (DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"} + DCGM_FI_DEV_FB_FREE{instance=~\"${instance}\", gpu=~\"${gpu}\"}) * 100",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used (Absolute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 32 },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "vGPU Liscense Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_VGPU_LICENSE_STATUS{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{modelName}} GPU ID: {{gpu}} Instance ID: {{GPU_I_ID}} Profile: {{GPU_I_PROFILE}}"
    }
   ]
  }
 ]
}